# The original base of this plugin was coded by Bulk and HotshotHD

name: CTF
author: EPICMC
main: CTF\CTF
description: CTF Plugin
version: 1.0.0
api: 2.0.0

commands:
  start:
    description: 
    permission: ctf.command.start

permissions:
  ctf.command.start:
    description: Allows to use /start
    default: op
